# Translation of Odoo Server.
# This file contains the translation of the following modules:
# * crm_enterprise
#
# Translators:
# Martin Trigaux, 2022
# Layna Nascimento, 2023
# Kevilyn Rosa, 2023
#
# "Dylan Kiss (dyki)" <dyki@odoo.com>, 2025.
# "MaitÃª Dietze (madi)" <madi@odoo.com>, 2025.
msgid ""
msgstr ""
"Project-Id-Version: Odoo Server 16.0+e\n"
"Report-Msgid-Bugs-To: \n"
"POT-Creation-Date: 2025-10-08 18:46+0000\n"
"PO-Revision-Date: 2025-10-13 14:59+0000\n"
"Last-Translator: \"MaitÃª Dietze (madi)\" <madi@odoo.com>\n"
"Language-Team: Portuguese (Brazil) <https://translate.odoo.com/projects/"
"odoo-19/crm_enterprise/pt_BR/>\n"
"Language: pt_BR\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: \n"
"Plural-Forms: nplurals=3; plural=(n == 0 || n == 1) ? 0 : ((n != 0 && n % "
"1000000 == 0) ? 1 : 2);\n"
"X-Generator: Weblate 5.12.2\n"

#. module: crm_enterprise
#. odoo-python
#: code:addons/crm_enterprise/tools/business_card_scanner.py:0
msgid "%(contact_name)s's opportunity"
msgstr "Oportunidade da %(contact_name)s"

#. module: crm_enterprise
#. odoo-python
#: code:addons/crm_enterprise/tools/business_card_scanner.py:0
msgid "Could not extract lead information from this image."
msgstr ""

#. module: crm_enterprise
#: model:ir.model,website_form_label:crm_enterprise.model_crm_lead
msgid "Create an Opportunity"
msgstr ""

#. module: crm_enterprise
#: model_terms:ir.ui.view,arch_db:crm_enterprise.crm_lead_view_map
msgid "Customer"
msgstr "Cliente"

#. module: crm_enterprise
#: model:ir.model.fields,field_description:crm_enterprise.field_crm_lead__days_to_convert
msgid "Days To Convert"
msgstr "Dias para converter"

#. module: crm_enterprise
#: model:ir.model.fields,field_description:crm_enterprise.field_crm_lead__display_name
msgid "Display Name"
msgstr ""

#. module: crm_enterprise
#: model:ir.model.fields,field_description:crm_enterprise.field_crm_lead__days_exceeding_closing
msgid "Exceeded Closing Days"
msgstr "Dias excedidos para fechamento"

#. module: crm_enterprise
#: model:ir.model.fields,field_description:crm_enterprise.field_crm_lead__id
msgid "ID"
msgstr ""

#. module: crm_enterprise
#. odoo-javascript
#: code:addons/crm_enterprise/static/src/crm_business_card_scanner.xml:0
#: code:addons/crm_enterprise/static/src/crm_business_card_scanner_cog_menu.xml:0
msgid "Import Business Cards"
msgstr ""

#. module: crm_enterprise
#: model:ir.model,name:crm_enterprise.model_crm_lead
msgid "Lead"
msgstr ""

#. module: crm_enterprise
#. odoo-python
#: code:addons/crm_enterprise/tools/business_card_scanner.py:0
msgid "Lead generated from this image."
msgstr ""

#. module: crm_enterprise
#: model_terms:ir.ui.view,arch_db:crm_enterprise.crm_lead_view_pivot
msgid "Leads"
msgstr "Leads"

#. module: crm_enterprise
#. odoo-python
#: code:addons/crm_enterprise/tools/business_card_scanner.py:0
msgid "Network error while processing the business cards."
msgstr ""

#. module: crm_enterprise
#. odoo-python
#: code:addons/crm_enterprise/tools/business_card_scanner.py:0
msgid "New Lead Scan"
msgstr ""

#. module: crm_enterprise
#: model_terms:ir.actions.act_window,help:crm_enterprise.crm_opportunity_action_dashboard
msgid "No data found!"
msgstr "Nenhum dado encontrado!"

#. module: crm_enterprise
#. odoo-python
#: code:addons/crm_enterprise/tools/business_card_scanner.py:0
msgid ""
"Oops, the AI service is not working ðŸ¤–. Please contact your administrator to "
"verify settings."
msgstr ""

#. module: crm_enterprise
#: model_terms:ir.ui.view,arch_db:crm_enterprise.crm_lead_view_cohort
#: model_terms:ir.ui.view,arch_db:crm_enterprise.crm_opportunity_view_graph
msgid "Opportunities"
msgstr "Oportunidades"

#. module: crm_enterprise
#: model:ir.actions.act_window,name:crm_enterprise.crm_opportunity_action_dashboard
msgid "Pipeline Analysis"
msgstr "AnÃ¡lise do funil"

#. module: crm_enterprise
#. odoo-javascript
#: code:addons/crm_enterprise/static/src/crm_business_card_scanner.xml:0
msgid "Scan Business Cards"
msgstr ""

#. module: crm_enterprise
#. odoo-python
#: code:addons/crm_enterprise/models/crm_lead.py:0
msgid ""
"The AI agent was not able to generate a lead from the provided image. *sad "
"robot noises* ðŸ¤–"
msgstr ""

#. module: crm_enterprise
#: model_terms:ir.actions.act_window,help:crm_enterprise.crm_opportunity_action_dashboard
msgid "Use this menu to have an overview of your Pipeline."
msgstr "Use esse menu para ter uma visÃ£o geral do seu funil."

#. module: crm_enterprise
#: model_terms:ir.ui.view,arch_db:crm_enterprise.crm_lead_view_graph
msgid "leads"
msgstr "leads"

#~ msgid "CRM Activity Analysis"
#~ msgstr "AnÃ¡lise de Atividade CRM"

#~ msgid "Is Won"
#~ msgstr "Ã‰ ganho"

#~ msgid "Lead/Opportunity"
#~ msgstr "Lead/Oportunidade"

#~ msgid "Lost"
#~ msgstr "Perdido"

#~ msgid "Pending"
#~ msgstr "Pendente"

#~ msgid "Won"
#~ msgstr "Ganhamos"
